name: Publish

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'README.md'
    - 'examples/**'
    - 'App.js'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Number Generator
        uses: einaregilsson/build-number@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}} 
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run build:prod
      - run: sed -i 's/\"version\": \"0.1.1\"/\"version\": \"0.1.${{ steps.buildnumber.outputs.build_number }}\"/g' package.json
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
